### ISSUE TITLE
0.1 release tag missing

### ISSUE THREAD

**Issue by ncopa** [bkoropoff/makekit#1]
There used to be a 0.1 release tarball when hosted on sourceforge. It would be nice to have a v0.1 tag at the point where 0.1 was done. (and maybe tag a 0.2 release?)

Releases are helpful for us who packages stuff for distros.

Thanks

**Comment by bkoropoff** [comment]
Whoops, I missed migrating the tags over.

**Comment by bkoropoff** [comment]
Should be fixed now.  Doing another release is probably a good idea...
