### ISSUE TITLE
.configure fails with strange error

### ISSUE THREAD

**Issue by laserswald** [bkoropoff/makekit#7]
I tried cloning makekit and when I tried to run ./configure, it fails with 
ERROR: please run configure from a seperate directory

What am I doing wrong?

**Comment by bkoropoff** [comment]
You have to run configure from a build directory other than the root of the project, e.g:

``` bash
$ mkdir out && cd out
$ ../configure
```

**Comment by laserswald** [comment]
I see. Thanks, man!
