### ISSUE TITLE
`makekit init` cannot find makekit script for copying

### ISSUE THREAD

**Issue by laserswald** [bkoropoff/makekit#8]
It looks for it in $MK_HOME, but that's not the same as where Makekit resides.

On my system, Makekit lives at /usr/local/bin/makekit. I've tried deciphering makekit puts itself in there, but I can't make heads or tails of exactly where it does so. Can you give me a quick point in the right direction?

**Comment by bkoropoff** [comment]
The installation list was missing a file.  It should work now.

**Comment by laserswald** [comment]
Thanks, Brian. Good job on everything else. This is set to become my build
system of choice.
